### ISSUE TITLE
Unhandled exception "Cannot read property 'toFixed' of undefined" at geojson.lib\lib\tools.js:37:17

### ISSUE THREAD

**Issue by ediaz-inteliti** [luscus/geojson.lib#4]
Hello,

I am experiencing an issue with the lib. I am using it with routeboxer lib, in a call of the function boxer.box(linestring, distanceOutOftheRoad); i am getting one exception because one coordinate is malformed in the way  [undefined,float]. I put a print log in the function positionPrecision (position, precision) like this:

```
function positionPrecision (position, precision) {
  return position.map(function(e) {
	  console.log(e);
    if (util.isArray(e)) {
      return positionPrecision(e, precision);
    }
	
    return 1 * e.toFixed(precision);
  });
}
```

Then i get the next log:

```
... huge coordinates log ....
[ -70.95804788620676, 36.803376634969084 ]
-70.95804788620676
36.803376634969084
-70.958
36.8034
[ -70.95804788620676, 36.758410554673155 ]
-70.95804788620676
36.758410554673155
[ undefined, 36.803376634969084 ]
undefined
TypeError: Cannot read property 'toFixed' of undefined
    at C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\node_modules\geojson.lib\lib\tools.js:37:17
    at Array.map (native)
    at positionPrecision (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\node_modules\geojson.lib\lib\tools.js:31:19)
    at C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\node_modules\geojson.lib\lib\tools.js:34:14
    at Array.map (native)
    at positionPrecision (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\node_modules\geojson.lib\lib\tools.js:31:19)
    at getBBoxFromVertices (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\node_modules\geojson.lib\lib\tools.js:100:14)
    at Object.getBBoxFromVertices (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\node_modules\geojson.lib\lib\tools.js:379:12)
    at RouteBoxer.getCellBounds_ (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\lib\geojson.lib.routeboxer.js:587:23)
    at RouteBoxer.mergeIntersectingCells_ (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\lib\geojson.lib.routeboxer.js:486:20)
    at RouteBoxer.box (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\geojson.lib.routeboxer\lib\geojson.lib.routeboxer.js:116:8)
    at C:\html5\dynamic-fuel-optimizer-backend-v1\app\middlewares\maps_worker.js:439:9
    at _stationsOnTheRoute (C:\html5\dynamic-fuel-optimizer-backend-v1\app\middlewares\maps_worker.js:420:9)
From previous event:
    at C:\html5\dynamic-fuel-optimizer-backend-v1\app\middlewares\maps_worker.js:179:6
From previous event:
    at routeDirections (C:\html5\dynamic-fuel-optimizer-backend-v1\app\middlewares\maps_worker.js:175:9)
    at C:\html5\dynamic-fuel-optimizer-backend-v1\app\middlewares\maps_worker.js:1426:13
From previous event:
    at C:\html5\dynamic-fuel-optimizer-backend-v1\app\middlewares\maps_worker.js:1424:8
    at tryCatcher (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\thinky\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\thinky\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\thinky\node_modules\bluebird\js\main\promise.js:581:18)
    at Async._drainQueue (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\thinky\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\thinky\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\html5\dynamic-fuel-optimizer-backend-v1\node_modules\thinky\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
info: ERRORError: TypeError: Cannot read property 'toFixed' of undefined
```
I dont know why, but i checked my linestring before send to box function and it dosnt has any malformed coordinate, is there any way how the linestring is modified?

Anyway, the function where the exception is throwed should be something to handle this condition...

Maybe something like
```
	if(isNaN(e))
	{
		return e;
	}
```

Thankyou for your atention and time.

**Comment by luscus** [comment]
do you get the LineString from "outside" meaning: you do not generate it with the lib in any way?

- If it comes from "outside" you should use `@mapbox/geojsonhint` to validate the geometries before processing
- If you generate it an one of the tool methods is broken (destinationPosition, intersectionPosition, ...), could you send a example? I would investigate it this weekend.

I may reactivate this package for myself in the future and I have started a redesign with tests and JSDoc for coding hints in the editors supporting it...

**Comment by kayschmitt** [comment]
I'm having issues with this same thing. I'm sending a list of coordiantes into the RouteBoxer and im getting an error on this same line. I've narrowed it down to RouteBoxer.prototype.getCellBounds_ of routeboxer. cell[0] + 1 is the same as this.lngGrid_.length so it produces undefined and therefore getting the toFixed error.

**Comment by kayschmitt** [comment]
I can send you what I coordinates I'm sending into the RouteBoxer.box() if that will help u debug the issue
